connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.driver-class=org.sqlite.JDBC
iceberg.jdbc-catalog.connection-url=jdbc:sqlite:/var/trino/iceberg-catalog.db
iceberg.jdbc-catalog.catalog-name=demo
iceberg.jdbc-catalog.default-warehouse-dir=s3://warehouse/
iceberg.jdbc-catalog.schema-version=V1
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.aws-access-key=admin
s3.aws-secret-key=minio123
s3.path-style-access=true
s3.region=us-east-1
