node.id=coordinator
node.environment=demo

coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=12GB
query.max-memory-per-node=10GB
query.client.timeout=30m
discovery.uri=http://localhost:8080

# Spooling protocol settings
protocol.spooling.enabled=true
protocol.spooling.shared-secret-key=jxTKysfCBuMZtFqUf8UJDQ1w9ez8rynEJsJqgJf66u0=
protocol.spooling.retrieval-mode=coordinator_proxy

# Arrow encoding support
protocol.spooling.encoding.arrow.enabled=true
protocol.spooling.encoding.arrow+zstd.enabled=true
protocol.spooling.encoding.json.enabled=true
protocol.spooling.encoding.json+zstd.enabled=true
protocol.spooling.encoding.json+lz4.enabled=true

# Disable http request log
http-server.log.enabled=false
http-server.authentication.allow-insecure-over-http=true
