spooling-manager.name=filesystem
fs.s3.enabled=true
fs.location=s3://spooling/
s3.endpoint=http://minio:9000
s3.aws-access-key=admin
s3.aws-secret-key=minio123
s3.path-style-access=true
fs.segment.encryption=false
