name: ci

on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          '3.9',
          '3.10',
          '3.11',
          '3.12',
          '3.13',
        ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libkrb5-dev
          pip install .[tests]

      - name: Run tests
        run: pytest -s tests/
