name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          # Quote the versions: https://github.com/actions/runner/issues/1989
          '3.7',
          '3.8',
          '3.9',
          '3.10',
          '3.11',
          '3.12',
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libkrb5-dev
          pip install .[tests]
      - name: Run tests
        run: |
          pytest -s tests/ integration_tests/
